// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outpost/proxy/v1/proxy.proto

package proxyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CompleteEnrollmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Token           string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceName      string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	WireguardPubkey string                 `protobuf:"bytes,3,opt,name=wireguard_pubkey,json=wireguardPubkey,proto3" json:"wireguard_pubkey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteEnrollmentRequest) Reset() {
	*x = CompleteEnrollmentRequest{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteEnrollmentRequest) ProtoMessage() {}

func (x *CompleteEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*CompleteEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteEnrollmentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CompleteEnrollmentRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *CompleteEnrollmentRequest) GetWireguardPubkey() string {
	if x != nil {
		return x.WireguardPubkey
	}
	return ""
}

type CompleteEnrollmentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AssignedIp     string                 `protobuf:"bytes,2,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	ServerPubkey   string                 `protobuf:"bytes,3,opt,name=server_pubkey,json=serverPubkey,proto3" json:"server_pubkey,omitempty"`
	ServerEndpoint string                 `protobuf:"bytes,4,opt,name=server_endpoint,json=serverEndpoint,proto3" json:"server_endpoint,omitempty"`
	DnsServers     []string               `protobuf:"bytes,5,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	AllowedIps     []string               `protobuf:"bytes,6,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Keepalive      int32                  `protobuf:"varint,7,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteEnrollmentResponse) Reset() {
	*x = CompleteEnrollmentResponse{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteEnrollmentResponse) ProtoMessage() {}

func (x *CompleteEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*CompleteEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteEnrollmentResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CompleteEnrollmentResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *CompleteEnrollmentResponse) GetServerPubkey() string {
	if x != nil {
		return x.ServerPubkey
	}
	return ""
}

func (x *CompleteEnrollmentResponse) GetServerEndpoint() string {
	if x != nil {
		return x.ServerEndpoint
	}
	return ""
}

func (x *CompleteEnrollmentResponse) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *CompleteEnrollmentResponse) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *CompleteEnrollmentResponse) GetKeepalive() int32 {
	if x != nil {
		return x.Keepalive
	}
	return 0
}

// Proxy -> Core
type ProxyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProxyEvent_AuthRequest
	//	*ProxyEvent_MfaResponse
	//	*ProxyEvent_Enrollment
	Event         isProxyEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEvent) Reset() {
	*x = ProxyEvent{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEvent) ProtoMessage() {}

func (x *ProxyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEvent.ProtoReflect.Descriptor instead.
func (*ProxyEvent) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyEvent) GetEvent() isProxyEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProxyEvent) GetAuthRequest() *AuthRequest {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *ProxyEvent) GetMfaResponse() *MFAResponse {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_MfaResponse); ok {
			return x.MfaResponse
		}
	}
	return nil
}

func (x *ProxyEvent) GetEnrollment() *EnrollmentEvent {
	if x != nil {
		if x, ok := x.Event.(*ProxyEvent_Enrollment); ok {
			return x.Enrollment
		}
	}
	return nil
}

type isProxyEvent_Event interface {
	isProxyEvent_Event()
}

type ProxyEvent_AuthRequest struct {
	AuthRequest *AuthRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type ProxyEvent_MfaResponse struct {
	MfaResponse *MFAResponse `protobuf:"bytes,2,opt,name=mfa_response,json=mfaResponse,proto3,oneof"`
}

type ProxyEvent_Enrollment struct {
	Enrollment *EnrollmentEvent `protobuf:"bytes,3,opt,name=enrollment,proto3,oneof"`
}

func (*ProxyEvent_AuthRequest) isProxyEvent_Event() {}

func (*ProxyEvent_MfaResponse) isProxyEvent_Event() {}

func (*ProxyEvent_Enrollment) isProxyEvent_Event() {}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type MFAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // totp, webauthn, email
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFAResponse) Reset() {
	*x = MFAResponse{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAResponse) ProtoMessage() {}

func (x *MFAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAResponse.ProtoReflect.Descriptor instead.
func (*MFAResponse) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *MFAResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MFAResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MFAResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type EnrollmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentEvent) Reset() {
	*x = EnrollmentEvent{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentEvent) ProtoMessage() {}

func (x *EnrollmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentEvent.ProtoReflect.Descriptor instead.
func (*EnrollmentEvent) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *EnrollmentEvent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollmentEvent) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *EnrollmentEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Core -> Proxy
type CoreProxyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*CoreProxyEvent_AuthResponse
	//	*CoreProxyEvent_MfaChallenge
	//	*CoreProxyEvent_EnrollmentStep
	Event         isCoreProxyEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreProxyEvent) Reset() {
	*x = CoreProxyEvent{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreProxyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreProxyEvent) ProtoMessage() {}

func (x *CoreProxyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreProxyEvent.ProtoReflect.Descriptor instead.
func (*CoreProxyEvent) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *CoreProxyEvent) GetEvent() isCoreProxyEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CoreProxyEvent) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Event.(*CoreProxyEvent_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *CoreProxyEvent) GetMfaChallenge() *MFAChallenge {
	if x != nil {
		if x, ok := x.Event.(*CoreProxyEvent_MfaChallenge); ok {
			return x.MfaChallenge
		}
	}
	return nil
}

func (x *CoreProxyEvent) GetEnrollmentStep() *EnrollmentStep {
	if x != nil {
		if x, ok := x.Event.(*CoreProxyEvent_EnrollmentStep); ok {
			return x.EnrollmentStep
		}
	}
	return nil
}

type isCoreProxyEvent_Event interface {
	isCoreProxyEvent_Event()
}

type CoreProxyEvent_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,1,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type CoreProxyEvent_MfaChallenge struct {
	MfaChallenge *MFAChallenge `protobuf:"bytes,2,opt,name=mfa_challenge,json=mfaChallenge,proto3,oneof"`
}

type CoreProxyEvent_EnrollmentStep struct {
	EnrollmentStep *EnrollmentStep `protobuf:"bytes,3,opt,name=enrollment_step,json=enrollmentStep,proto3,oneof"`
}

func (*CoreProxyEvent_AuthResponse) isCoreProxyEvent_Event() {}

func (*CoreProxyEvent_MfaChallenge) isCoreProxyEvent_Event() {}

func (*CoreProxyEvent_EnrollmentStep) isCoreProxyEvent_Event() {}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	MfaRequired   bool                   `protobuf:"varint,5,opt,name=mfa_required,json=mfaRequired,proto3" json:"mfa_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuthResponse) GetMfaRequired() bool {
	if x != nil {
		return x.MfaRequired
	}
	return false
}

type MFAChallenge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AvailableMethods []string               `protobuf:"bytes,2,rep,name=available_methods,json=availableMethods,proto3" json:"available_methods,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MFAChallenge) Reset() {
	*x = MFAChallenge{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAChallenge) ProtoMessage() {}

func (x *MFAChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAChallenge.ProtoReflect.Descriptor instead.
func (*MFAChallenge) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *MFAChallenge) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MFAChallenge) GetAvailableMethods() []string {
	if x != nil {
		return x.AvailableMethods
	}
	return nil
}

func (x *MFAChallenge) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnrollmentStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentStep) Reset() {
	*x = EnrollmentStep{}
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentStep) ProtoMessage() {}

func (x *EnrollmentStep) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_proxy_v1_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentStep.ProtoReflect.Descriptor instead.
func (*EnrollmentStep) Descriptor() ([]byte, []int) {
	return file_outpost_proxy_v1_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *EnrollmentStep) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *EnrollmentStep) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnrollmentStep) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

var File_outpost_proxy_v1_proxy_proto protoreflect.FileDescriptor

const file_outpost_proxy_v1_proxy_proto_rawDesc = "" +
	"\n" +
	"\x1coutpost/proxy/v1/proxy.proto\x12\x10outpost.proxy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xb3\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"}\n" +
	"\x19CompleteEnrollmentRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12)\n" +
	"\x10wireguard_pubkey\x18\x03 \x01(\tR\x0fwireguardPubkey\"\x88\x02\n" +
	"\x1aCompleteEnrollmentResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vassigned_ip\x18\x02 \x01(\tR\n" +
	"assignedIp\x12#\n" +
	"\rserver_pubkey\x18\x03 \x01(\tR\fserverPubkey\x12'\n" +
	"\x0fserver_endpoint\x18\x04 \x01(\tR\x0eserverEndpoint\x12\x1f\n" +
	"\vdns_servers\x18\x05 \x03(\tR\n" +
	"dnsServers\x12\x1f\n" +
	"\vallowed_ips\x18\x06 \x03(\tR\n" +
	"allowedIps\x12\x1c\n" +
	"\tkeepalive\x18\a \x01(\x05R\tkeepalive\"\xe2\x01\n" +
	"\n" +
	"ProxyEvent\x12B\n" +
	"\fauth_request\x18\x01 \x01(\v2\x1d.outpost.proxy.v1.AuthRequestH\x00R\vauthRequest\x12B\n" +
	"\fmfa_response\x18\x02 \x01(\v2\x1d.outpost.proxy.v1.MFAResponseH\x00R\vmfaResponse\x12C\n" +
	"\n" +
	"enrollment\x18\x03 \x01(\v2!.outpost.proxy.v1.EnrollmentEventH\x00R\n" +
	"enrollmentB\a\n" +
	"\x05event\"\x81\x01\n" +
	"\vAuthRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\"X\n" +
	"\vMFAResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"U\n" +
	"\x0fEnrollmentEvent\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xf4\x01\n" +
	"\x0eCoreProxyEvent\x12E\n" +
	"\rauth_response\x18\x01 \x01(\v2\x1e.outpost.proxy.v1.AuthResponseH\x00R\fauthResponse\x12E\n" +
	"\rmfa_challenge\x18\x02 \x01(\v2\x1e.outpost.proxy.v1.MFAChallengeH\x00R\fmfaChallenge\x12K\n" +
	"\x0fenrollment_step\x18\x03 \x01(\v2 .outpost.proxy.v1.EnrollmentStepH\x00R\x0eenrollmentStepB\a\n" +
	"\x05event\"\xb4\x01\n" +
	"\fAuthResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\fmfa_required\x18\x05 \x01(\bR\vmfaRequired\"t\n" +
	"\fMFAChallenge\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x11available_methods\x18\x02 \x03(\tR\x10availableMethods\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Z\n" +
	"\x0eEnrollmentStep\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete2\xba\x02\n" +
	"\fProxyService\x12M\n" +
	"\aConnect\x12\x1c.outpost.proxy.v1.ProxyEvent\x1a .outpost.proxy.v1.CoreProxyEvent(\x010\x01\x12j\n" +
	"\x17ValidateEnrollmentToken\x12&.outpost.proxy.v1.ValidateTokenRequest\x1a'.outpost.proxy.v1.ValidateTokenResponse\x12o\n" +
	"\x12CompleteEnrollment\x12+.outpost.proxy.v1.CompleteEnrollmentRequest\x1a,.outpost.proxy.v1.CompleteEnrollmentResponseB>Z<github.com/romashqua/outpost/pkg/pb/outpost/proxy/v1;proxyv1b\x06proto3"

var (
	file_outpost_proxy_v1_proxy_proto_rawDescOnce sync.Once
	file_outpost_proxy_v1_proxy_proto_rawDescData []byte
)

func file_outpost_proxy_v1_proxy_proto_rawDescGZIP() []byte {
	file_outpost_proxy_v1_proxy_proto_rawDescOnce.Do(func() {
		file_outpost_proxy_v1_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outpost_proxy_v1_proxy_proto_rawDesc), len(file_outpost_proxy_v1_proxy_proto_rawDesc)))
	})
	return file_outpost_proxy_v1_proxy_proto_rawDescData
}

var file_outpost_proxy_v1_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_outpost_proxy_v1_proxy_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),       // 0: outpost.proxy.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),      // 1: outpost.proxy.v1.ValidateTokenResponse
	(*CompleteEnrollmentRequest)(nil),  // 2: outpost.proxy.v1.CompleteEnrollmentRequest
	(*CompleteEnrollmentResponse)(nil), // 3: outpost.proxy.v1.CompleteEnrollmentResponse
	(*ProxyEvent)(nil),                 // 4: outpost.proxy.v1.ProxyEvent
	(*AuthRequest)(nil),                // 5: outpost.proxy.v1.AuthRequest
	(*MFAResponse)(nil),                // 6: outpost.proxy.v1.MFAResponse
	(*EnrollmentEvent)(nil),            // 7: outpost.proxy.v1.EnrollmentEvent
	(*CoreProxyEvent)(nil),             // 8: outpost.proxy.v1.CoreProxyEvent
	(*AuthResponse)(nil),               // 9: outpost.proxy.v1.AuthResponse
	(*MFAChallenge)(nil),               // 10: outpost.proxy.v1.MFAChallenge
	(*EnrollmentStep)(nil),             // 11: outpost.proxy.v1.EnrollmentStep
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_outpost_proxy_v1_proxy_proto_depIdxs = []int32{
	12, // 0: outpost.proxy.v1.ValidateTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 1: outpost.proxy.v1.ProxyEvent.auth_request:type_name -> outpost.proxy.v1.AuthRequest
	6,  // 2: outpost.proxy.v1.ProxyEvent.mfa_response:type_name -> outpost.proxy.v1.MFAResponse
	7,  // 3: outpost.proxy.v1.ProxyEvent.enrollment:type_name -> outpost.proxy.v1.EnrollmentEvent
	9,  // 4: outpost.proxy.v1.CoreProxyEvent.auth_response:type_name -> outpost.proxy.v1.AuthResponse
	10, // 5: outpost.proxy.v1.CoreProxyEvent.mfa_challenge:type_name -> outpost.proxy.v1.MFAChallenge
	11, // 6: outpost.proxy.v1.CoreProxyEvent.enrollment_step:type_name -> outpost.proxy.v1.EnrollmentStep
	4,  // 7: outpost.proxy.v1.ProxyService.Connect:input_type -> outpost.proxy.v1.ProxyEvent
	0,  // 8: outpost.proxy.v1.ProxyService.ValidateEnrollmentToken:input_type -> outpost.proxy.v1.ValidateTokenRequest
	2,  // 9: outpost.proxy.v1.ProxyService.CompleteEnrollment:input_type -> outpost.proxy.v1.CompleteEnrollmentRequest
	8,  // 10: outpost.proxy.v1.ProxyService.Connect:output_type -> outpost.proxy.v1.CoreProxyEvent
	1,  // 11: outpost.proxy.v1.ProxyService.ValidateEnrollmentToken:output_type -> outpost.proxy.v1.ValidateTokenResponse
	3,  // 12: outpost.proxy.v1.ProxyService.CompleteEnrollment:output_type -> outpost.proxy.v1.CompleteEnrollmentResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_outpost_proxy_v1_proxy_proto_init() }
func file_outpost_proxy_v1_proxy_proto_init() {
	if File_outpost_proxy_v1_proxy_proto != nil {
		return
	}
	file_outpost_proxy_v1_proxy_proto_msgTypes[4].OneofWrappers = []any{
		(*ProxyEvent_AuthRequest)(nil),
		(*ProxyEvent_MfaResponse)(nil),
		(*ProxyEvent_Enrollment)(nil),
	}
	file_outpost_proxy_v1_proxy_proto_msgTypes[8].OneofWrappers = []any{
		(*CoreProxyEvent_AuthResponse)(nil),
		(*CoreProxyEvent_MfaChallenge)(nil),
		(*CoreProxyEvent_EnrollmentStep)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outpost_proxy_v1_proxy_proto_rawDesc), len(file_outpost_proxy_v1_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outpost_proxy_v1_proxy_proto_goTypes,
		DependencyIndexes: file_outpost_proxy_v1_proxy_proto_depIdxs,
		MessageInfos:      file_outpost_proxy_v1_proxy_proto_msgTypes,
	}.Build()
	File_outpost_proxy_v1_proxy_proto = out.File
	file_outpost_proxy_v1_proxy_proto_goTypes = nil
	file_outpost_proxy_v1_proxy_proto_depIdxs = nil
}
