// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: outpost/proxy/v1/proxy.proto

package proxyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyService_Connect_FullMethodName                 = "/outpost.proxy.v1.ProxyService/Connect"
	ProxyService_ValidateEnrollmentToken_FullMethodName = "/outpost.proxy.v1.ProxyService/ValidateEnrollmentToken"
	ProxyService_CompleteEnrollment_FullMethodName      = "/outpost.proxy.v1.ProxyService/CompleteEnrollment"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyServiceClient interface {
	// Proxy connects to core to handle enrollment and auth flows.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyEvent, CoreProxyEvent], error)
	// Validate an enrollment token.
	ValidateEnrollmentToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// Complete device enrollment.
	CompleteEnrollment(ctx context.Context, in *CompleteEnrollmentRequest, opts ...grpc.CallOption) (*CompleteEnrollmentResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyEvent, CoreProxyEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProxyService_ServiceDesc.Streams[0], ProxyService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyEvent, CoreProxyEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyService_ConnectClient = grpc.BidiStreamingClient[ProxyEvent, CoreProxyEvent]

func (c *proxyServiceClient) ValidateEnrollmentToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, ProxyService_ValidateEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) CompleteEnrollment(ctx context.Context, in *CompleteEnrollmentRequest, opts ...grpc.CallOption) (*CompleteEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteEnrollmentResponse)
	err := c.cc.Invoke(ctx, ProxyService_CompleteEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
type ProxyServiceServer interface {
	// Proxy connects to core to handle enrollment and auth flows.
	Connect(grpc.BidiStreamingServer[ProxyEvent, CoreProxyEvent]) error
	// Validate an enrollment token.
	ValidateEnrollmentToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// Complete device enrollment.
	CompleteEnrollment(context.Context, *CompleteEnrollmentRequest) (*CompleteEnrollmentResponse, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) Connect(grpc.BidiStreamingServer[ProxyEvent, CoreProxyEvent]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProxyServiceServer) ValidateEnrollmentToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateEnrollmentToken not implemented")
}
func (UnimplementedProxyServiceServer) CompleteEnrollment(context.Context, *CompleteEnrollmentRequest) (*CompleteEnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteEnrollment not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServiceServer).Connect(&grpc.GenericServerStream[ProxyEvent, CoreProxyEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyService_ConnectServer = grpc.BidiStreamingServer[ProxyEvent, CoreProxyEvent]

func _ProxyService_ValidateEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).ValidateEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_ValidateEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).ValidateEnrollmentToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_CompleteEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).CompleteEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_CompleteEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).CompleteEnrollment(ctx, req.(*CompleteEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outpost.proxy.v1.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateEnrollmentToken",
			Handler:    _ProxyService_ValidateEnrollmentToken_Handler,
		},
		{
			MethodName: "CompleteEnrollment",
			Handler:    _ProxyService_CompleteEnrollment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ProxyService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "outpost/proxy/v1/proxy.proto",
}
