// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outpost/gateway/v1/gateway.proto

package gatewayv1

import (
	v1 "github.com/romashqua/outpost/pkg/pb/outpost/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerUpdate_Action int32

const (
	PeerUpdate_ACTION_UNSPECIFIED PeerUpdate_Action = 0
	PeerUpdate_ACTION_ADD         PeerUpdate_Action = 1
	PeerUpdate_ACTION_MODIFY      PeerUpdate_Action = 2
	PeerUpdate_ACTION_REMOVE      PeerUpdate_Action = 3
)

// Enum value maps for PeerUpdate_Action.
var (
	PeerUpdate_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ADD",
		2: "ACTION_MODIFY",
		3: "ACTION_REMOVE",
	}
	PeerUpdate_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ADD":         1,
		"ACTION_MODIFY":      2,
		"ACTION_REMOVE":      3,
	}
)

func (x PeerUpdate_Action) Enum() *PeerUpdate_Action {
	p := new(PeerUpdate_Action)
	*p = x
	return p
}

func (x PeerUpdate_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerUpdate_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_outpost_gateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (PeerUpdate_Action) Type() protoreflect.EnumType {
	return &file_outpost_gateway_v1_gateway_proto_enumTypes[0]
}

func (x PeerUpdate_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerUpdate_Action.Descriptor instead.
func (PeerUpdate_Action) EnumDescriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{10, 0}
}

type S2SUpdate_Action int32

const (
	S2SUpdate_ACTION_UNSPECIFIED   S2SUpdate_Action = 0
	S2SUpdate_ACTION_ADD_TUNNEL    S2SUpdate_Action = 1
	S2SUpdate_ACTION_REMOVE_TUNNEL S2SUpdate_Action = 2
	S2SUpdate_ACTION_UPDATE_PEERS  S2SUpdate_Action = 3
	S2SUpdate_ACTION_UPDATE_ROUTES S2SUpdate_Action = 4
)

// Enum value maps for S2SUpdate_Action.
var (
	S2SUpdate_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ADD_TUNNEL",
		2: "ACTION_REMOVE_TUNNEL",
		3: "ACTION_UPDATE_PEERS",
		4: "ACTION_UPDATE_ROUTES",
	}
	S2SUpdate_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":   0,
		"ACTION_ADD_TUNNEL":    1,
		"ACTION_REMOVE_TUNNEL": 2,
		"ACTION_UPDATE_PEERS":  3,
		"ACTION_UPDATE_ROUTES": 4,
	}
)

func (x S2SUpdate_Action) Enum() *S2SUpdate_Action {
	p := new(S2SUpdate_Action)
	*p = x
	return p
}

func (x S2SUpdate_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S2SUpdate_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_outpost_gateway_v1_gateway_proto_enumTypes[1].Descriptor()
}

func (S2SUpdate_Action) Type() protoreflect.EnumType {
	return &file_outpost_gateway_v1_gateway_proto_enumTypes[1]
}

func (x S2SUpdate_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S2SUpdate_Action.Descriptor instead.
func (S2SUpdate_Action) EnumDescriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{11, 0}
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayToken  string                 `protobuf:"bytes,1,opt,name=gateway_token,json=gatewayToken,proto3" json:"gateway_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigRequest) GetGatewayToken() string {
	if x != nil {
		return x.GatewayToken
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayId      string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ConnectedPeers int32                  `protobuf:"varint,4,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HeartbeatRequest) GetConnectedPeers() int32 {
	if x != nil {
		return x.ConnectedPeers
	}
	return 0
}

type GatewayConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	NetworkName   string                 `protobuf:"bytes,2,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ListenPort    int32                  `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Addresses     []string               `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Peers         []*v1.Peer             `protobuf:"bytes,6,rep,name=peers,proto3" json:"peers,omitempty"`
	Firewall      *v1.FirewallConfig     `protobuf:"bytes,7,opt,name=firewall,proto3" json:"firewall,omitempty"`
	S2STunnels    []*S2STunnelConfig     `protobuf:"bytes,8,rep,name=s2s_tunnels,json=s2sTunnels,proto3" json:"s2s_tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayConfig) Reset() {
	*x = GatewayConfig{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfig) ProtoMessage() {}

func (x *GatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfig.ProtoReflect.Descriptor instead.
func (*GatewayConfig) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayConfig) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayConfig) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *GatewayConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GatewayConfig) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *GatewayConfig) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GatewayConfig) GetPeers() []*v1.Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GatewayConfig) GetFirewall() *v1.FirewallConfig {
	if x != nil {
		return x.Firewall
	}
	return nil
}

func (x *GatewayConfig) GetS2STunnels() []*S2STunnelConfig {
	if x != nil {
		return x.S2STunnels
	}
	return nil
}

type S2STunnelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ListenPort    int32                  `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Peers         []*S2SPeer             `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	LocalSubnets  []string               `protobuf:"bytes,6,rep,name=local_subnets,json=localSubnets,proto3" json:"local_subnets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2STunnelConfig) Reset() {
	*x = S2STunnelConfig{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2STunnelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2STunnelConfig) ProtoMessage() {}

func (x *S2STunnelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2STunnelConfig.ProtoReflect.Descriptor instead.
func (*S2STunnelConfig) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *S2STunnelConfig) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *S2STunnelConfig) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *S2STunnelConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *S2STunnelConfig) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *S2STunnelConfig) GetPeers() []*S2SPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *S2STunnelConfig) GetLocalSubnets() []string {
	if x != nil {
		return x.LocalSubnets
	}
	return nil
}

type S2SPeer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GatewayId           string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	PublicKey           string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint            string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PersistentKeepalive int32                  `protobuf:"varint,5,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *S2SPeer) Reset() {
	*x = S2SPeer{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SPeer) ProtoMessage() {}

func (x *S2SPeer) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SPeer.ProtoReflect.Descriptor instead.
func (*S2SPeer) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *S2SPeer) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *S2SPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *S2SPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S2SPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *S2SPeer) GetPersistentKeepalive() int32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

// Gateway -> Core
type GatewayEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*GatewayEvent_Stats
	//	*GatewayEvent_S2SHealth
	//	*GatewayEvent_Status
	Event         isGatewayEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayEvent) Reset() {
	*x = GatewayEvent{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayEvent) ProtoMessage() {}

func (x *GatewayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayEvent.ProtoReflect.Descriptor instead.
func (*GatewayEvent) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayEvent) GetEvent() isGatewayEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GatewayEvent) GetStats() *PeerStatsReport {
	if x != nil {
		if x, ok := x.Event.(*GatewayEvent_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *GatewayEvent) GetS2SHealth() *S2SHealthReport {
	if x != nil {
		if x, ok := x.Event.(*GatewayEvent_S2SHealth); ok {
			return x.S2SHealth
		}
	}
	return nil
}

func (x *GatewayEvent) GetStatus() *GatewayStatusReport {
	if x != nil {
		if x, ok := x.Event.(*GatewayEvent_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isGatewayEvent_Event interface {
	isGatewayEvent_Event()
}

type GatewayEvent_Stats struct {
	Stats *PeerStatsReport `protobuf:"bytes,1,opt,name=stats,proto3,oneof"`
}

type GatewayEvent_S2SHealth struct {
	S2SHealth *S2SHealthReport `protobuf:"bytes,2,opt,name=s2s_health,json=s2sHealth,proto3,oneof"`
}

type GatewayEvent_Status struct {
	Status *GatewayStatusReport `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

func (*GatewayEvent_Stats) isGatewayEvent_Event() {}

func (*GatewayEvent_S2SHealth) isGatewayEvent_Event() {}

func (*GatewayEvent_Status) isGatewayEvent_Event() {}

type PeerStatsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*v1.PeerStats        `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatsReport) Reset() {
	*x = PeerStatsReport{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatsReport) ProtoMessage() {}

func (x *PeerStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatsReport.ProtoReflect.Descriptor instead.
func (*PeerStatsReport) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *PeerStatsReport) GetPeers() []*v1.PeerStats {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerStatsReport) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

type S2SHealthReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TunnelId        string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	RemoteGatewayId string                 `protobuf:"bytes,2,opt,name=remote_gateway_id,json=remoteGatewayId,proto3" json:"remote_gateway_id,omitempty"`
	IsHealthy       bool                   `protobuf:"varint,3,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CheckedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S2SHealthReport) Reset() {
	*x = S2SHealthReport{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SHealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SHealthReport) ProtoMessage() {}

func (x *S2SHealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SHealthReport.ProtoReflect.Descriptor instead.
func (*S2SHealthReport) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *S2SHealthReport) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *S2SHealthReport) GetRemoteGatewayId() string {
	if x != nil {
		return x.RemoteGatewayId
	}
	return ""
}

func (x *S2SHealthReport) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *S2SHealthReport) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *S2SHealthReport) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

type GatewayStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivePeers   int32                  `protobuf:"varint,1,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	RxBytesTotal  int64                  `protobuf:"varint,2,opt,name=rx_bytes_total,json=rxBytesTotal,proto3" json:"rx_bytes_total,omitempty"`
	TxBytesTotal  int64                  `protobuf:"varint,3,opt,name=tx_bytes_total,json=txBytesTotal,proto3" json:"tx_bytes_total,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayStatusReport) Reset() {
	*x = GatewayStatusReport{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatusReport) ProtoMessage() {}

func (x *GatewayStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatusReport.ProtoReflect.Descriptor instead.
func (*GatewayStatusReport) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GatewayStatusReport) GetActivePeers() int32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

func (x *GatewayStatusReport) GetRxBytesTotal() int64 {
	if x != nil {
		return x.RxBytesTotal
	}
	return 0
}

func (x *GatewayStatusReport) GetTxBytesTotal() int64 {
	if x != nil {
		return x.TxBytesTotal
	}
	return 0
}

func (x *GatewayStatusReport) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GatewayStatusReport) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// Core -> Gateway
type CoreEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*CoreEvent_PeerUpdate
	//	*CoreEvent_S2SUpdate
	//	*CoreEvent_FirewallUpdate
	//	*CoreEvent_FullResync
	Event         isCoreEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreEvent) Reset() {
	*x = CoreEvent{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreEvent) ProtoMessage() {}

func (x *CoreEvent) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreEvent.ProtoReflect.Descriptor instead.
func (*CoreEvent) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *CoreEvent) GetEvent() isCoreEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CoreEvent) GetPeerUpdate() *PeerUpdate {
	if x != nil {
		if x, ok := x.Event.(*CoreEvent_PeerUpdate); ok {
			return x.PeerUpdate
		}
	}
	return nil
}

func (x *CoreEvent) GetS2SUpdate() *S2SUpdate {
	if x != nil {
		if x, ok := x.Event.(*CoreEvent_S2SUpdate); ok {
			return x.S2SUpdate
		}
	}
	return nil
}

func (x *CoreEvent) GetFirewallUpdate() *FirewallUpdate {
	if x != nil {
		if x, ok := x.Event.(*CoreEvent_FirewallUpdate); ok {
			return x.FirewallUpdate
		}
	}
	return nil
}

func (x *CoreEvent) GetFullResync() *FullResync {
	if x != nil {
		if x, ok := x.Event.(*CoreEvent_FullResync); ok {
			return x.FullResync
		}
	}
	return nil
}

type isCoreEvent_Event interface {
	isCoreEvent_Event()
}

type CoreEvent_PeerUpdate struct {
	PeerUpdate *PeerUpdate `protobuf:"bytes,1,opt,name=peer_update,json=peerUpdate,proto3,oneof"`
}

type CoreEvent_S2SUpdate struct {
	S2SUpdate *S2SUpdate `protobuf:"bytes,2,opt,name=s2s_update,json=s2sUpdate,proto3,oneof"`
}

type CoreEvent_FirewallUpdate struct {
	FirewallUpdate *FirewallUpdate `protobuf:"bytes,3,opt,name=firewall_update,json=firewallUpdate,proto3,oneof"`
}

type CoreEvent_FullResync struct {
	FullResync *FullResync `protobuf:"bytes,4,opt,name=full_resync,json=fullResync,proto3,oneof"`
}

func (*CoreEvent_PeerUpdate) isCoreEvent_Event() {}

func (*CoreEvent_S2SUpdate) isCoreEvent_Event() {}

func (*CoreEvent_FirewallUpdate) isCoreEvent_Event() {}

func (*CoreEvent_FullResync) isCoreEvent_Event() {}

type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        PeerUpdate_Action      `protobuf:"varint,1,opt,name=action,proto3,enum=outpost.gateway.v1.PeerUpdate_Action" json:"action,omitempty"`
	Peer          *v1.Peer               `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *PeerUpdate) GetAction() PeerUpdate_Action {
	if x != nil {
		return x.Action
	}
	return PeerUpdate_ACTION_UNSPECIFIED
}

func (x *PeerUpdate) GetPeer() *v1.Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type S2SUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        S2SUpdate_Action       `protobuf:"varint,1,opt,name=action,proto3,enum=outpost.gateway.v1.S2SUpdate_Action" json:"action,omitempty"`
	Tunnel        *S2STunnelConfig       `protobuf:"bytes,2,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2SUpdate) Reset() {
	*x = S2SUpdate{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SUpdate) ProtoMessage() {}

func (x *S2SUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SUpdate.ProtoReflect.Descriptor instead.
func (*S2SUpdate) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *S2SUpdate) GetAction() S2SUpdate_Action {
	if x != nil {
		return x.Action
	}
	return S2SUpdate_ACTION_UNSPECIFIED
}

func (x *S2SUpdate) GetTunnel() *S2STunnelConfig {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type FirewallUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *v1.FirewallConfig     `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallUpdate) Reset() {
	*x = FirewallUpdate{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallUpdate) ProtoMessage() {}

func (x *FirewallUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallUpdate.ProtoReflect.Descriptor instead.
func (*FirewallUpdate) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *FirewallUpdate) GetConfig() *v1.FirewallConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type FullResync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *GatewayConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullResync) Reset() {
	*x = FullResync{}
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullResync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullResync) ProtoMessage() {}

func (x *FullResync) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullResync.ProtoReflect.Descriptor instead.
func (*FullResync) Descriptor() ([]byte, []int) {
	return file_outpost_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *FullResync) GetConfig() *GatewayConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_outpost_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_outpost_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	" outpost/gateway/v1/gateway.proto\x12\x12outpost.gateway.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1doutpost/common/v1/types.proto\"4\n" +
	"\rConfigRequest\x12#\n" +
	"\rgateway_token\x18\x01 \x01(\tR\fgatewayToken\"\xbb\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0fconnected_peers\x18\x04 \x01(\x05R\x0econnectedPeers\"\xe5\x02\n" +
	"\rGatewayConfig\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12!\n" +
	"\fnetwork_name\x18\x02 \x01(\tR\vnetworkName\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\x05R\n" +
	"listenPort\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12-\n" +
	"\x05peers\x18\x06 \x03(\v2\x17.outpost.common.v1.PeerR\x05peers\x12=\n" +
	"\bfirewall\x18\a \x01(\v2!.outpost.common.v1.FirewallConfigR\bfirewall\x12D\n" +
	"\vs2s_tunnels\x18\b \x03(\v2#.outpost.gateway.v1.S2STunnelConfigR\n" +
	"s2sTunnels\"\xef\x01\n" +
	"\x0fS2STunnelConfig\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\x05R\n" +
	"listenPort\x121\n" +
	"\x05peers\x18\x05 \x03(\v2\x1b.outpost.gateway.v1.S2SPeerR\x05peers\x12#\n" +
	"\rlocal_subnets\x18\x06 \x03(\tR\flocalSubnets\"\xb7\x01\n" +
	"\aS2SPeer\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x121\n" +
	"\x14persistent_keepalive\x18\x05 \x01(\x05R\x13persistentKeepalive\"\xdd\x01\n" +
	"\fGatewayEvent\x12;\n" +
	"\x05stats\x18\x01 \x01(\v2#.outpost.gateway.v1.PeerStatsReportH\x00R\x05stats\x12D\n" +
	"\n" +
	"s2s_health\x18\x02 \x01(\v2#.outpost.gateway.v1.S2SHealthReportH\x00R\ts2sHealth\x12A\n" +
	"\x06status\x18\x03 \x01(\v2'.outpost.gateway.v1.GatewayStatusReportH\x00R\x06statusB\a\n" +
	"\x05event\"\x84\x01\n" +
	"\x0fPeerStatsReport\x122\n" +
	"\x05peers\x18\x01 \x03(\v2\x1c.outpost.common.v1.PeerStatsR\x05peers\x12=\n" +
	"\fcollected_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"\xd3\x01\n" +
	"\x0fS2SHealthReport\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12*\n" +
	"\x11remote_gateway_id\x18\x02 \x01(\tR\x0fremoteGatewayId\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x03 \x01(\bR\tisHealthy\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x129\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\xc4\x01\n" +
	"\x13GatewayStatusReport\x12!\n" +
	"\factive_peers\x18\x01 \x01(\x05R\vactivePeers\x12$\n" +
	"\x0erx_bytes_total\x18\x02 \x01(\x03R\frxBytesTotal\x12$\n" +
	"\x0etx_bytes_total\x18\x03 \x01(\x03R\ftxBytesTotal\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\"\xa9\x02\n" +
	"\tCoreEvent\x12A\n" +
	"\vpeer_update\x18\x01 \x01(\v2\x1e.outpost.gateway.v1.PeerUpdateH\x00R\n" +
	"peerUpdate\x12>\n" +
	"\n" +
	"s2s_update\x18\x02 \x01(\v2\x1d.outpost.gateway.v1.S2SUpdateH\x00R\ts2sUpdate\x12M\n" +
	"\x0ffirewall_update\x18\x03 \x01(\v2\".outpost.gateway.v1.FirewallUpdateH\x00R\x0efirewallUpdate\x12A\n" +
	"\vfull_resync\x18\x04 \x01(\v2\x1e.outpost.gateway.v1.FullResyncH\x00R\n" +
	"fullResyncB\a\n" +
	"\x05event\"\xd0\x01\n" +
	"\n" +
	"PeerUpdate\x12=\n" +
	"\x06action\x18\x01 \x01(\x0e2%.outpost.gateway.v1.PeerUpdate.ActionR\x06action\x12+\n" +
	"\x04peer\x18\x02 \x01(\v2\x17.outpost.common.v1.PeerR\x04peer\"V\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ACTION_ADD\x10\x01\x12\x11\n" +
	"\rACTION_MODIFY\x10\x02\x12\x11\n" +
	"\rACTION_REMOVE\x10\x03\"\x8d\x02\n" +
	"\tS2SUpdate\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.outpost.gateway.v1.S2SUpdate.ActionR\x06action\x12;\n" +
	"\x06tunnel\x18\x02 \x01(\v2#.outpost.gateway.v1.S2STunnelConfigR\x06tunnel\"\x84\x01\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_ADD_TUNNEL\x10\x01\x12\x18\n" +
	"\x14ACTION_REMOVE_TUNNEL\x10\x02\x12\x17\n" +
	"\x13ACTION_UPDATE_PEERS\x10\x03\x12\x18\n" +
	"\x14ACTION_UPDATE_ROUTES\x10\x04\"K\n" +
	"\x0eFirewallUpdate\x129\n" +
	"\x06config\x18\x01 \x01(\v2!.outpost.common.v1.FirewallConfigR\x06config\"G\n" +
	"\n" +
	"FullResync\x129\n" +
	"\x06config\x18\x01 \x01(\v2!.outpost.gateway.v1.GatewayConfigR\x06config2\xfb\x01\n" +
	"\x0eGatewayService\x12Q\n" +
	"\tGetConfig\x12!.outpost.gateway.v1.ConfigRequest\x1a!.outpost.gateway.v1.GatewayConfig\x12K\n" +
	"\x04Sync\x12 .outpost.gateway.v1.GatewayEvent\x1a\x1d.outpost.gateway.v1.CoreEvent(\x010\x01\x12I\n" +
	"\tHeartbeat\x12$.outpost.gateway.v1.HeartbeatRequest\x1a\x16.google.protobuf.EmptyBBZ@github.com/romashqua/outpost/pkg/pb/outpost/gateway/v1;gatewayv1b\x06proto3"

var (
	file_outpost_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_outpost_gateway_v1_gateway_proto_rawDescData []byte
)

func file_outpost_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_outpost_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_outpost_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outpost_gateway_v1_gateway_proto_rawDesc), len(file_outpost_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_outpost_gateway_v1_gateway_proto_rawDescData
}

var file_outpost_gateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_outpost_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_outpost_gateway_v1_gateway_proto_goTypes = []any{
	(PeerUpdate_Action)(0),        // 0: outpost.gateway.v1.PeerUpdate.Action
	(S2SUpdate_Action)(0),         // 1: outpost.gateway.v1.S2SUpdate.Action
	(*ConfigRequest)(nil),         // 2: outpost.gateway.v1.ConfigRequest
	(*HeartbeatRequest)(nil),      // 3: outpost.gateway.v1.HeartbeatRequest
	(*GatewayConfig)(nil),         // 4: outpost.gateway.v1.GatewayConfig
	(*S2STunnelConfig)(nil),       // 5: outpost.gateway.v1.S2STunnelConfig
	(*S2SPeer)(nil),               // 6: outpost.gateway.v1.S2SPeer
	(*GatewayEvent)(nil),          // 7: outpost.gateway.v1.GatewayEvent
	(*PeerStatsReport)(nil),       // 8: outpost.gateway.v1.PeerStatsReport
	(*S2SHealthReport)(nil),       // 9: outpost.gateway.v1.S2SHealthReport
	(*GatewayStatusReport)(nil),   // 10: outpost.gateway.v1.GatewayStatusReport
	(*CoreEvent)(nil),             // 11: outpost.gateway.v1.CoreEvent
	(*PeerUpdate)(nil),            // 12: outpost.gateway.v1.PeerUpdate
	(*S2SUpdate)(nil),             // 13: outpost.gateway.v1.S2SUpdate
	(*FirewallUpdate)(nil),        // 14: outpost.gateway.v1.FirewallUpdate
	(*FullResync)(nil),            // 15: outpost.gateway.v1.FullResync
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*v1.Peer)(nil),               // 17: outpost.common.v1.Peer
	(*v1.FirewallConfig)(nil),     // 18: outpost.common.v1.FirewallConfig
	(*v1.PeerStats)(nil),          // 19: outpost.common.v1.PeerStats
	(*emptypb.Empty)(nil),         // 20: google.protobuf.Empty
}
var file_outpost_gateway_v1_gateway_proto_depIdxs = []int32{
	16, // 0: outpost.gateway.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	17, // 1: outpost.gateway.v1.GatewayConfig.peers:type_name -> outpost.common.v1.Peer
	18, // 2: outpost.gateway.v1.GatewayConfig.firewall:type_name -> outpost.common.v1.FirewallConfig
	5,  // 3: outpost.gateway.v1.GatewayConfig.s2s_tunnels:type_name -> outpost.gateway.v1.S2STunnelConfig
	6,  // 4: outpost.gateway.v1.S2STunnelConfig.peers:type_name -> outpost.gateway.v1.S2SPeer
	8,  // 5: outpost.gateway.v1.GatewayEvent.stats:type_name -> outpost.gateway.v1.PeerStatsReport
	9,  // 6: outpost.gateway.v1.GatewayEvent.s2s_health:type_name -> outpost.gateway.v1.S2SHealthReport
	10, // 7: outpost.gateway.v1.GatewayEvent.status:type_name -> outpost.gateway.v1.GatewayStatusReport
	19, // 8: outpost.gateway.v1.PeerStatsReport.peers:type_name -> outpost.common.v1.PeerStats
	16, // 9: outpost.gateway.v1.PeerStatsReport.collected_at:type_name -> google.protobuf.Timestamp
	16, // 10: outpost.gateway.v1.S2SHealthReport.checked_at:type_name -> google.protobuf.Timestamp
	12, // 11: outpost.gateway.v1.CoreEvent.peer_update:type_name -> outpost.gateway.v1.PeerUpdate
	13, // 12: outpost.gateway.v1.CoreEvent.s2s_update:type_name -> outpost.gateway.v1.S2SUpdate
	14, // 13: outpost.gateway.v1.CoreEvent.firewall_update:type_name -> outpost.gateway.v1.FirewallUpdate
	15, // 14: outpost.gateway.v1.CoreEvent.full_resync:type_name -> outpost.gateway.v1.FullResync
	0,  // 15: outpost.gateway.v1.PeerUpdate.action:type_name -> outpost.gateway.v1.PeerUpdate.Action
	17, // 16: outpost.gateway.v1.PeerUpdate.peer:type_name -> outpost.common.v1.Peer
	1,  // 17: outpost.gateway.v1.S2SUpdate.action:type_name -> outpost.gateway.v1.S2SUpdate.Action
	5,  // 18: outpost.gateway.v1.S2SUpdate.tunnel:type_name -> outpost.gateway.v1.S2STunnelConfig
	18, // 19: outpost.gateway.v1.FirewallUpdate.config:type_name -> outpost.common.v1.FirewallConfig
	4,  // 20: outpost.gateway.v1.FullResync.config:type_name -> outpost.gateway.v1.GatewayConfig
	2,  // 21: outpost.gateway.v1.GatewayService.GetConfig:input_type -> outpost.gateway.v1.ConfigRequest
	7,  // 22: outpost.gateway.v1.GatewayService.Sync:input_type -> outpost.gateway.v1.GatewayEvent
	3,  // 23: outpost.gateway.v1.GatewayService.Heartbeat:input_type -> outpost.gateway.v1.HeartbeatRequest
	4,  // 24: outpost.gateway.v1.GatewayService.GetConfig:output_type -> outpost.gateway.v1.GatewayConfig
	11, // 25: outpost.gateway.v1.GatewayService.Sync:output_type -> outpost.gateway.v1.CoreEvent
	20, // 26: outpost.gateway.v1.GatewayService.Heartbeat:output_type -> google.protobuf.Empty
	24, // [24:27] is the sub-list for method output_type
	21, // [21:24] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_outpost_gateway_v1_gateway_proto_init() }
func file_outpost_gateway_v1_gateway_proto_init() {
	if File_outpost_gateway_v1_gateway_proto != nil {
		return
	}
	file_outpost_gateway_v1_gateway_proto_msgTypes[5].OneofWrappers = []any{
		(*GatewayEvent_Stats)(nil),
		(*GatewayEvent_S2SHealth)(nil),
		(*GatewayEvent_Status)(nil),
	}
	file_outpost_gateway_v1_gateway_proto_msgTypes[9].OneofWrappers = []any{
		(*CoreEvent_PeerUpdate)(nil),
		(*CoreEvent_S2SUpdate)(nil),
		(*CoreEvent_FirewallUpdate)(nil),
		(*CoreEvent_FullResync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outpost_gateway_v1_gateway_proto_rawDesc), len(file_outpost_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outpost_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_outpost_gateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_outpost_gateway_v1_gateway_proto_enumTypes,
		MessageInfos:      file_outpost_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_outpost_gateway_v1_gateway_proto = out.File
	file_outpost_gateway_v1_gateway_proto_goTypes = nil
	file_outpost_gateway_v1_gateway_proto_depIdxs = nil
}
