apiVersion: v1
kind: Service
metadata:
  name: {{ include "outpost.fullname" . }}-core
  labels:
    {{- include "outpost.labels" . | nindent 4 }}
    {{- include "outpost.selectorLabels" (dict "root" . "component" "core") | nindent 4 }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - name: http
      port: {{ .Values.core.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.core.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "outpost.selectorLabels" (dict "root" . "component" "core") | nindent 4 }}
