{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "outpost.fullname" . }}-gateway
  labels:
    {{- include "outpost.labels" . | nindent 4 }}
    {{- include "outpost.selectorLabels" (dict "root" . "component" "gateway") | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: wireguard
      port: {{ .Values.gateway.service.port }}
      targetPort: wireguard
      protocol: UDP
  selector:
    {{- include "outpost.selectorLabels" (dict "root" . "component" "gateway") | nindent 4 }}
{{- end }}
