apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outpost.secretName" . }}
  labels:
    {{- include "outpost.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | b64enc | quote }}
  {{- if .Values.secret.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | b64enc | quote }}
  {{- end }}
