// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outpost/common/v1/types.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FirewallRule_Action int32

const (
	FirewallRule_ACTION_UNSPECIFIED FirewallRule_Action = 0
	FirewallRule_ACTION_ACCEPT      FirewallRule_Action = 1
	FirewallRule_ACTION_DROP        FirewallRule_Action = 2
)

// Enum value maps for FirewallRule_Action.
var (
	FirewallRule_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ACCEPT",
		2: "ACTION_DROP",
	}
	FirewallRule_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ACCEPT":      1,
		"ACTION_DROP":        2,
	}
)

func (x FirewallRule_Action) Enum() *FirewallRule_Action {
	p := new(FirewallRule_Action)
	*p = x
	return p
}

func (x FirewallRule_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirewallRule_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_outpost_common_v1_types_proto_enumTypes[0].Descriptor()
}

func (FirewallRule_Action) Type() protoreflect.EnumType {
	return &file_outpost_common_v1_types_proto_enumTypes[0]
}

func (x FirewallRule_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirewallRule_Action.Descriptor instead.
func (FirewallRule_Action) EnumDescriptor() ([]byte, []int) {
	return file_outpost_common_v1_types_proto_rawDescGZIP(), []int{2, 0}
}

type Peer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,2,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PresharedKey        string                 `protobuf:"bytes,3,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	PersistentKeepalive int32                  `protobuf:"varint,4,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	Endpoint            string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_outpost_common_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_common_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_outpost_common_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Peer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *Peer) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *Peer) GetPersistentKeepalive() int32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

func (x *Peer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type PeerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	RxBytes       int64                  `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       int64                  `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshake *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStats) Reset() {
	*x = PeerStats{}
	mi := &file_outpost_common_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStats) ProtoMessage() {}

func (x *PeerStats) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_common_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStats.ProtoReflect.Descriptor instead.
func (*PeerStats) Descriptor() ([]byte, []int) {
	return file_outpost_common_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *PeerStats) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerStats) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerStats) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PeerStats) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PeerStats) GetLastHandshake() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshake
	}
	return nil
}

type FirewallRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          string                 `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Action        FirewallRule_Action    `protobuf:"varint,5,opt,name=action,proto3,enum=outpost.common.v1.FirewallRule_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallRule) Reset() {
	*x = FirewallRule{}
	mi := &file_outpost_common_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallRule) ProtoMessage() {}

func (x *FirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_common_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallRule.ProtoReflect.Descriptor instead.
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return file_outpost_common_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *FirewallRule) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FirewallRule) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *FirewallRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FirewallRule) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *FirewallRule) GetAction() FirewallRule_Action {
	if x != nil {
		return x.Action
	}
	return FirewallRule_ACTION_UNSPECIFIED
}

type FirewallConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*FirewallRule        `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	NatEnabled    bool                   `protobuf:"varint,2,opt,name=nat_enabled,json=natEnabled,proto3" json:"nat_enabled,omitempty"`
	NatInterface  string                 `protobuf:"bytes,3,opt,name=nat_interface,json=natInterface,proto3" json:"nat_interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallConfig) Reset() {
	*x = FirewallConfig{}
	mi := &file_outpost_common_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallConfig) ProtoMessage() {}

func (x *FirewallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_common_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallConfig.ProtoReflect.Descriptor instead.
func (*FirewallConfig) Descriptor() ([]byte, []int) {
	return file_outpost_common_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *FirewallConfig) GetRules() []*FirewallRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *FirewallConfig) GetNatEnabled() bool {
	if x != nil {
		return x.NatEnabled
	}
	return false
}

func (x *FirewallConfig) GetNatInterface() string {
	if x != nil {
		return x.NatInterface
	}
	return ""
}

var File_outpost_common_v1_types_proto protoreflect.FileDescriptor

const file_outpost_common_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1doutpost/common/v1/types.proto\x12\x11outpost.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\x04Peer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x02 \x03(\tR\n" +
	"allowedIps\x12#\n" +
	"\rpreshared_key\x18\x03 \x01(\tR\fpresharedKey\x121\n" +
	"\x14persistent_keepalive\x18\x04 \x01(\x05R\x13persistentKeepalive\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\"\xbf\x01\n" +
	"\tPeerStats\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x03R\atxBytes\x12A\n" +
	"\x0elast_handshake\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHandshake\"\xfe\x01\n" +
	"\fFirewallRule\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\x12>\n" +
	"\x06action\x18\x05 \x01(\x0e2&.outpost.common.v1.FirewallRule.ActionR\x06action\"D\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_ACCEPT\x10\x01\x12\x0f\n" +
	"\vACTION_DROP\x10\x02\"\x8d\x01\n" +
	"\x0eFirewallConfig\x125\n" +
	"\x05rules\x18\x01 \x03(\v2\x1f.outpost.common.v1.FirewallRuleR\x05rules\x12\x1f\n" +
	"\vnat_enabled\x18\x02 \x01(\bR\n" +
	"natEnabled\x12#\n" +
	"\rnat_interface\x18\x03 \x01(\tR\fnatInterfaceB@Z>github.com/romashqua/outpost/pkg/pb/outpost/common/v1;commonv1b\x06proto3"

var (
	file_outpost_common_v1_types_proto_rawDescOnce sync.Once
	file_outpost_common_v1_types_proto_rawDescData []byte
)

func file_outpost_common_v1_types_proto_rawDescGZIP() []byte {
	file_outpost_common_v1_types_proto_rawDescOnce.Do(func() {
		file_outpost_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outpost_common_v1_types_proto_rawDesc), len(file_outpost_common_v1_types_proto_rawDesc)))
	})
	return file_outpost_common_v1_types_proto_rawDescData
}

var file_outpost_common_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_outpost_common_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_outpost_common_v1_types_proto_goTypes = []any{
	(FirewallRule_Action)(0),      // 0: outpost.common.v1.FirewallRule.Action
	(*Peer)(nil),                  // 1: outpost.common.v1.Peer
	(*PeerStats)(nil),             // 2: outpost.common.v1.PeerStats
	(*FirewallRule)(nil),          // 3: outpost.common.v1.FirewallRule
	(*FirewallConfig)(nil),        // 4: outpost.common.v1.FirewallConfig
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_outpost_common_v1_types_proto_depIdxs = []int32{
	5, // 0: outpost.common.v1.PeerStats.last_handshake:type_name -> google.protobuf.Timestamp
	0, // 1: outpost.common.v1.FirewallRule.action:type_name -> outpost.common.v1.FirewallRule.Action
	3, // 2: outpost.common.v1.FirewallConfig.rules:type_name -> outpost.common.v1.FirewallRule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_outpost_common_v1_types_proto_init() }
func file_outpost_common_v1_types_proto_init() {
	if File_outpost_common_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outpost_common_v1_types_proto_rawDesc), len(file_outpost_common_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outpost_common_v1_types_proto_goTypes,
		DependencyIndexes: file_outpost_common_v1_types_proto_depIdxs,
		EnumInfos:         file_outpost_common_v1_types_proto_enumTypes,
		MessageInfos:      file_outpost_common_v1_types_proto_msgTypes,
	}.Build()
	File_outpost_common_v1_types_proto = out.File
	file_outpost_common_v1_types_proto_goTypes = nil
	file_outpost_common_v1_types_proto_depIdxs = nil
}
