// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outpost/s2s/v1/s2s.proto

package s2sv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteTableUpdate_Action int32

const (
	RouteTableUpdate_ACTION_UNSPECIFIED RouteTableUpdate_Action = 0
	RouteTableUpdate_ACTION_ADD         RouteTableUpdate_Action = 1
	RouteTableUpdate_ACTION_REMOVE      RouteTableUpdate_Action = 2
	RouteTableUpdate_ACTION_REPLACE     RouteTableUpdate_Action = 3 // full table replacement
)

// Enum value maps for RouteTableUpdate_Action.
var (
	RouteTableUpdate_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ADD",
		2: "ACTION_REMOVE",
		3: "ACTION_REPLACE",
	}
	RouteTableUpdate_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ADD":         1,
		"ACTION_REMOVE":      2,
		"ACTION_REPLACE":     3,
	}
)

func (x RouteTableUpdate_Action) Enum() *RouteTableUpdate_Action {
	p := new(RouteTableUpdate_Action)
	*p = x
	return p
}

func (x RouteTableUpdate_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteTableUpdate_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_outpost_s2s_v1_s2s_proto_enumTypes[0].Descriptor()
}

func (RouteTableUpdate_Action) Type() protoreflect.EnumType {
	return &file_outpost_s2s_v1_s2s_proto_enumTypes[0]
}

func (x RouteTableUpdate_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteTableUpdate_Action.Descriptor instead.
func (RouteTableUpdate_Action) EnumDescriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{4, 0}
}

type RouteAdvertisement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	TunnelId      string                 `protobuf:"bytes,2,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Routes        []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteAdvertisement) Reset() {
	*x = RouteAdvertisement{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAdvertisement) ProtoMessage() {}

func (x *RouteAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAdvertisement.ProtoReflect.Descriptor instead.
func (*RouteAdvertisement) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{0}
}

func (x *RouteAdvertisement) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RouteAdvertisement) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RouteAdvertisement) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteAdvertisement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"` // CIDR notation
	Metric        int32                  `protobuf:"varint,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Route) GetMetric() int32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Route) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type RouteAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RoutesAccepted int32                  `protobuf:"varint,2,opt,name=routes_accepted,json=routesAccepted,proto3" json:"routes_accepted,omitempty"`
	RoutesRejected int32                  `protobuf:"varint,3,opt,name=routes_rejected,json=routesRejected,proto3" json:"routes_rejected,omitempty"`
	Errors         []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteAck) Reset() {
	*x = RouteAck{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAck) ProtoMessage() {}

func (x *RouteAck) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAck.ProtoReflect.Descriptor instead.
func (*RouteAck) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{2}
}

func (x *RouteAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RouteAck) GetRoutesAccepted() int32 {
	if x != nil {
		return x.RoutesAccepted
	}
	return 0
}

func (x *RouteAck) GetRoutesRejected() int32 {
	if x != nil {
		return x.RoutesRejected
	}
	return 0
}

func (x *RouteAck) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type RouteSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	TunnelId      string                 `protobuf:"bytes,2,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSubscription) Reset() {
	*x = RouteSubscription{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSubscription) ProtoMessage() {}

func (x *RouteSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSubscription.ProtoReflect.Descriptor instead.
func (*RouteSubscription) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{3}
}

func (x *RouteSubscription) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RouteSubscription) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type RouteTableUpdate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Action        RouteTableUpdate_Action `protobuf:"varint,1,opt,name=action,proto3,enum=outpost.s2s.v1.RouteTableUpdate_Action" json:"action,omitempty"`
	Routes        []*RouteEntry           `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTableUpdate) Reset() {
	*x = RouteTableUpdate{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTableUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableUpdate) ProtoMessage() {}

func (x *RouteTableUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableUpdate.ProtoReflect.Descriptor instead.
func (*RouteTableUpdate) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{4}
}

func (x *RouteTableUpdate) GetAction() RouteTableUpdate_Action {
	if x != nil {
		return x.Action
	}
	return RouteTableUpdate_ACTION_UNSPECIFIED
}

func (x *RouteTableUpdate) GetRoutes() []*RouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteTableUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RouteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ViaGatewayId  string                 `protobuf:"bytes,2,opt,name=via_gateway_id,json=viaGatewayId,proto3" json:"via_gateway_id,omitempty"`
	ViaPublicKey  string                 `protobuf:"bytes,3,opt,name=via_public_key,json=viaPublicKey,proto3" json:"via_public_key,omitempty"`
	ViaEndpoint   string                 `protobuf:"bytes,4,opt,name=via_endpoint,json=viaEndpoint,proto3" json:"via_endpoint,omitempty"`
	Metric        int32                  `protobuf:"varint,5,opt,name=metric,proto3" json:"metric,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{5}
}

func (x *RouteEntry) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteEntry) GetViaGatewayId() string {
	if x != nil {
		return x.ViaGatewayId
	}
	return ""
}

func (x *RouteEntry) GetViaPublicKey() string {
	if x != nil {
		return x.ViaPublicKey
	}
	return ""
}

func (x *RouteEntry) GetViaEndpoint() string {
	if x != nil {
		return x.ViaEndpoint
	}
	return ""
}

func (x *RouteEntry) GetMetric() int32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *RouteEntry) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type TunnelHealthReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	TunnelId      string                 `protobuf:"bytes,2,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Peers         []*TunnelPeerHealth    `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelHealthReport) Reset() {
	*x = TunnelHealthReport{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelHealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelHealthReport) ProtoMessage() {}

func (x *TunnelHealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelHealthReport.ProtoReflect.Descriptor instead.
func (*TunnelHealthReport) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelHealthReport) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *TunnelHealthReport) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelHealthReport) GetPeers() []*TunnelPeerHealth {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *TunnelHealthReport) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

type TunnelPeerHealth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RemoteGatewayId string                 `protobuf:"bytes,1,opt,name=remote_gateway_id,json=remoteGatewayId,proto3" json:"remote_gateway_id,omitempty"`
	IsReachable     bool                   `protobuf:"varint,2,opt,name=is_reachable,json=isReachable,proto3" json:"is_reachable,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	RxBytes         int64                  `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes         int64                  `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshake   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TunnelPeerHealth) Reset() {
	*x = TunnelPeerHealth{}
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelPeerHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPeerHealth) ProtoMessage() {}

func (x *TunnelPeerHealth) ProtoReflect() protoreflect.Message {
	mi := &file_outpost_s2s_v1_s2s_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPeerHealth.ProtoReflect.Descriptor instead.
func (*TunnelPeerHealth) Descriptor() ([]byte, []int) {
	return file_outpost_s2s_v1_s2s_proto_rawDescGZIP(), []int{7}
}

func (x *TunnelPeerHealth) GetRemoteGatewayId() string {
	if x != nil {
		return x.RemoteGatewayId
	}
	return ""
}

func (x *TunnelPeerHealth) GetIsReachable() bool {
	if x != nil {
		return x.IsReachable
	}
	return false
}

func (x *TunnelPeerHealth) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TunnelPeerHealth) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *TunnelPeerHealth) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *TunnelPeerHealth) GetLastHandshake() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshake
	}
	return nil
}

var File_outpost_s2s_v1_s2s_proto protoreflect.FileDescriptor

const file_outpost_s2s_v1_s2s_proto_rawDesc = "" +
	"\n" +
	"\x18outpost/s2s/v1/s2s.proto\x12\x0eoutpost.s2s.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x12RouteAdvertisement\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1b\n" +
	"\ttunnel_id\x18\x02 \x01(\tR\btunnelId\x12-\n" +
	"\x06routes\x18\x03 \x03(\v2\x15.outpost.s2s.v1.RouteR\x06routes\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc7\x01\n" +
	"\x05Route\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\x05R\x06metric\x12E\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2%.outpost.s2s.v1.Route.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\bRouteAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12'\n" +
	"\x0froutes_accepted\x18\x02 \x01(\x05R\x0eroutesAccepted\x12'\n" +
	"\x0froutes_rejected\x18\x03 \x01(\x05R\x0eroutesRejected\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"O\n" +
	"\x11RouteSubscription\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1b\n" +
	"\ttunnel_id\x18\x02 \x01(\tR\btunnelId\"\x9a\x02\n" +
	"\x10RouteTableUpdate\x12?\n" +
	"\x06action\x18\x01 \x01(\x0e2'.outpost.s2s.v1.RouteTableUpdate.ActionR\x06action\x122\n" +
	"\x06routes\x18\x02 \x03(\v2\x1a.outpost.s2s.v1.RouteEntryR\x06routes\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"W\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ACTION_ADD\x10\x01\x12\x11\n" +
	"\rACTION_REMOVE\x10\x02\x12\x12\n" +
	"\x0eACTION_REPLACE\x10\x03\"\xd2\x01\n" +
	"\n" +
	"RouteEntry\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12$\n" +
	"\x0evia_gateway_id\x18\x02 \x01(\tR\fviaGatewayId\x12$\n" +
	"\x0evia_public_key\x18\x03 \x01(\tR\fviaPublicKey\x12!\n" +
	"\fvia_endpoint\x18\x04 \x01(\tR\vviaEndpoint\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\x05R\x06metric\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"\xc3\x01\n" +
	"\x12TunnelHealthReport\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1b\n" +
	"\ttunnel_id\x18\x02 \x01(\tR\btunnelId\x126\n" +
	"\x05peers\x18\x03 \x03(\v2 .outpost.s2s.v1.TunnelPeerHealthR\x05peers\x129\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\xf9\x01\n" +
	"\x10TunnelPeerHealth\x12*\n" +
	"\x11remote_gateway_id\x18\x01 \x01(\tR\x0fremoteGatewayId\x12!\n" +
	"\fis_reachable\x18\x02 \x01(\bR\visReachable\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x19\n" +
	"\brx_bytes\x18\x04 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x03R\atxBytes\x12A\n" +
	"\x0elast_handshake\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHandshake2\x88\x02\n" +
	"\x0fS2SControlPlane\x12O\n" +
	"\x0fAdvertiseRoutes\x12\".outpost.s2s.v1.RouteAdvertisement\x1a\x18.outpost.s2s.v1.RouteAck\x12X\n" +
	"\x0fSubscribeRoutes\x12!.outpost.s2s.v1.RouteSubscription\x1a .outpost.s2s.v1.RouteTableUpdate0\x01\x12J\n" +
	"\fReportHealth\x12\".outpost.s2s.v1.TunnelHealthReport\x1a\x16.google.protobuf.EmptyB:Z8github.com/romashqua/outpost/pkg/pb/outpost/s2s/v1;s2sv1b\x06proto3"

var (
	file_outpost_s2s_v1_s2s_proto_rawDescOnce sync.Once
	file_outpost_s2s_v1_s2s_proto_rawDescData []byte
)

func file_outpost_s2s_v1_s2s_proto_rawDescGZIP() []byte {
	file_outpost_s2s_v1_s2s_proto_rawDescOnce.Do(func() {
		file_outpost_s2s_v1_s2s_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outpost_s2s_v1_s2s_proto_rawDesc), len(file_outpost_s2s_v1_s2s_proto_rawDesc)))
	})
	return file_outpost_s2s_v1_s2s_proto_rawDescData
}

var file_outpost_s2s_v1_s2s_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_outpost_s2s_v1_s2s_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_outpost_s2s_v1_s2s_proto_goTypes = []any{
	(RouteTableUpdate_Action)(0),  // 0: outpost.s2s.v1.RouteTableUpdate.Action
	(*RouteAdvertisement)(nil),    // 1: outpost.s2s.v1.RouteAdvertisement
	(*Route)(nil),                 // 2: outpost.s2s.v1.Route
	(*RouteAck)(nil),              // 3: outpost.s2s.v1.RouteAck
	(*RouteSubscription)(nil),     // 4: outpost.s2s.v1.RouteSubscription
	(*RouteTableUpdate)(nil),      // 5: outpost.s2s.v1.RouteTableUpdate
	(*RouteEntry)(nil),            // 6: outpost.s2s.v1.RouteEntry
	(*TunnelHealthReport)(nil),    // 7: outpost.s2s.v1.TunnelHealthReport
	(*TunnelPeerHealth)(nil),      // 8: outpost.s2s.v1.TunnelPeerHealth
	nil,                           // 9: outpost.s2s.v1.Route.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_outpost_s2s_v1_s2s_proto_depIdxs = []int32{
	2,  // 0: outpost.s2s.v1.RouteAdvertisement.routes:type_name -> outpost.s2s.v1.Route
	10, // 1: outpost.s2s.v1.RouteAdvertisement.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 2: outpost.s2s.v1.Route.attributes:type_name -> outpost.s2s.v1.Route.AttributesEntry
	0,  // 3: outpost.s2s.v1.RouteTableUpdate.action:type_name -> outpost.s2s.v1.RouteTableUpdate.Action
	6,  // 4: outpost.s2s.v1.RouteTableUpdate.routes:type_name -> outpost.s2s.v1.RouteEntry
	10, // 5: outpost.s2s.v1.RouteTableUpdate.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 6: outpost.s2s.v1.TunnelHealthReport.peers:type_name -> outpost.s2s.v1.TunnelPeerHealth
	10, // 7: outpost.s2s.v1.TunnelHealthReport.checked_at:type_name -> google.protobuf.Timestamp
	10, // 8: outpost.s2s.v1.TunnelPeerHealth.last_handshake:type_name -> google.protobuf.Timestamp
	1,  // 9: outpost.s2s.v1.S2SControlPlane.AdvertiseRoutes:input_type -> outpost.s2s.v1.RouteAdvertisement
	4,  // 10: outpost.s2s.v1.S2SControlPlane.SubscribeRoutes:input_type -> outpost.s2s.v1.RouteSubscription
	7,  // 11: outpost.s2s.v1.S2SControlPlane.ReportHealth:input_type -> outpost.s2s.v1.TunnelHealthReport
	3,  // 12: outpost.s2s.v1.S2SControlPlane.AdvertiseRoutes:output_type -> outpost.s2s.v1.RouteAck
	5,  // 13: outpost.s2s.v1.S2SControlPlane.SubscribeRoutes:output_type -> outpost.s2s.v1.RouteTableUpdate
	11, // 14: outpost.s2s.v1.S2SControlPlane.ReportHealth:output_type -> google.protobuf.Empty
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_outpost_s2s_v1_s2s_proto_init() }
func file_outpost_s2s_v1_s2s_proto_init() {
	if File_outpost_s2s_v1_s2s_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outpost_s2s_v1_s2s_proto_rawDesc), len(file_outpost_s2s_v1_s2s_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outpost_s2s_v1_s2s_proto_goTypes,
		DependencyIndexes: file_outpost_s2s_v1_s2s_proto_depIdxs,
		EnumInfos:         file_outpost_s2s_v1_s2s_proto_enumTypes,
		MessageInfos:      file_outpost_s2s_v1_s2s_proto_msgTypes,
	}.Build()
	File_outpost_s2s_v1_s2s_proto = out.File
	file_outpost_s2s_v1_s2s_proto_goTypes = nil
	file_outpost_s2s_v1_s2s_proto_depIdxs = nil
}
