// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: outpost/s2s/v1/s2s.proto

package s2sv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	S2SControlPlane_AdvertiseRoutes_FullMethodName = "/outpost.s2s.v1.S2SControlPlane/AdvertiseRoutes"
	S2SControlPlane_SubscribeRoutes_FullMethodName = "/outpost.s2s.v1.S2SControlPlane/SubscribeRoutes"
	S2SControlPlane_ReportHealth_FullMethodName    = "/outpost.s2s.v1.S2SControlPlane/ReportHealth"
)

// S2SControlPlaneClient is the client API for S2SControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type S2SControlPlaneClient interface {
	// Gateway advertises its local routes to core.
	AdvertiseRoutes(ctx context.Context, in *RouteAdvertisement, opts ...grpc.CallOption) (*RouteAck, error)
	// Gateway subscribes to route table updates from core.
	SubscribeRoutes(ctx context.Context, in *RouteSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteTableUpdate], error)
	// Gateway reports tunnel health status.
	ReportHealth(ctx context.Context, in *TunnelHealthReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type s2SControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewS2SControlPlaneClient(cc grpc.ClientConnInterface) S2SControlPlaneClient {
	return &s2SControlPlaneClient{cc}
}

func (c *s2SControlPlaneClient) AdvertiseRoutes(ctx context.Context, in *RouteAdvertisement, opts ...grpc.CallOption) (*RouteAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteAck)
	err := c.cc.Invoke(ctx, S2SControlPlane_AdvertiseRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s2SControlPlaneClient) SubscribeRoutes(ctx context.Context, in *RouteSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RouteTableUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &S2SControlPlane_ServiceDesc.Streams[0], S2SControlPlane_SubscribeRoutes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RouteSubscription, RouteTableUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S2SControlPlane_SubscribeRoutesClient = grpc.ServerStreamingClient[RouteTableUpdate]

func (c *s2SControlPlaneClient) ReportHealth(ctx context.Context, in *TunnelHealthReport, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, S2SControlPlane_ReportHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S2SControlPlaneServer is the server API for S2SControlPlane service.
// All implementations must embed UnimplementedS2SControlPlaneServer
// for forward compatibility.
type S2SControlPlaneServer interface {
	// Gateway advertises its local routes to core.
	AdvertiseRoutes(context.Context, *RouteAdvertisement) (*RouteAck, error)
	// Gateway subscribes to route table updates from core.
	SubscribeRoutes(*RouteSubscription, grpc.ServerStreamingServer[RouteTableUpdate]) error
	// Gateway reports tunnel health status.
	ReportHealth(context.Context, *TunnelHealthReport) (*emptypb.Empty, error)
	mustEmbedUnimplementedS2SControlPlaneServer()
}

// UnimplementedS2SControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedS2SControlPlaneServer struct{}

func (UnimplementedS2SControlPlaneServer) AdvertiseRoutes(context.Context, *RouteAdvertisement) (*RouteAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertiseRoutes not implemented")
}
func (UnimplementedS2SControlPlaneServer) SubscribeRoutes(*RouteSubscription, grpc.ServerStreamingServer[RouteTableUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRoutes not implemented")
}
func (UnimplementedS2SControlPlaneServer) ReportHealth(context.Context, *TunnelHealthReport) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealth not implemented")
}
func (UnimplementedS2SControlPlaneServer) mustEmbedUnimplementedS2SControlPlaneServer() {}
func (UnimplementedS2SControlPlaneServer) testEmbeddedByValue()                         {}

// UnsafeS2SControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S2SControlPlaneServer will
// result in compilation errors.
type UnsafeS2SControlPlaneServer interface {
	mustEmbedUnimplementedS2SControlPlaneServer()
}

func RegisterS2SControlPlaneServer(s grpc.ServiceRegistrar, srv S2SControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedS2SControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&S2SControlPlane_ServiceDesc, srv)
}

func _S2SControlPlane_AdvertiseRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteAdvertisement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S2SControlPlaneServer).AdvertiseRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S2SControlPlane_AdvertiseRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S2SControlPlaneServer).AdvertiseRoutes(ctx, req.(*RouteAdvertisement))
	}
	return interceptor(ctx, in, info, handler)
}

func _S2SControlPlane_SubscribeRoutes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RouteSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(S2SControlPlaneServer).SubscribeRoutes(m, &grpc.GenericServerStream[RouteSubscription, RouteTableUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S2SControlPlane_SubscribeRoutesServer = grpc.ServerStreamingServer[RouteTableUpdate]

func _S2SControlPlane_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelHealthReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S2SControlPlaneServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S2SControlPlane_ReportHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S2SControlPlaneServer).ReportHealth(ctx, req.(*TunnelHealthReport))
	}
	return interceptor(ctx, in, info, handler)
}

// S2SControlPlane_ServiceDesc is the grpc.ServiceDesc for S2SControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S2SControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outpost.s2s.v1.S2SControlPlane",
	HandlerType: (*S2SControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdvertiseRoutes",
			Handler:    _S2SControlPlane_AdvertiseRoutes_Handler,
		},
		{
			MethodName: "ReportHealth",
			Handler:    _S2SControlPlane_ReportHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRoutes",
			Handler:       _S2SControlPlane_SubscribeRoutes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "outpost/s2s/v1/s2s.proto",
}
